#!/bin/sh

cp -R . /src
cd /opt/workflows/$WORKFLOW/cue

# copy dependencies to the source directory
cp -R ../assets /assets

# initialize and update dagger.
dagger project init
dagger project update

# fetch the trustacks cue library.
git clone https://github.com/TruStacks/cue.git ./cue.mod/pkg/trustacks.io

dagger do "$1" --log-format=plain