version: '3.9'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sleep", "infinity"]
    environment:
      BUILDKIT_HOST: tcp://buildkitd:1234
    volumes:
    - ..:/workspace:cached
  buildkitd:
    image: moby/buildkit:rootless
    command:
    - --oci-worker-no-process-sandbox
    - --addr
    - tcp://0.0.0.0:1234
    security_opt:
    - seccomp=unconfined
    - apparmor=unconfined
    restart: always